
print ("# generated by make-code-item003.py")

# 幾號機	FT001		噸位	力劲400	人員	罗玉春		日期	16年8月19日																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						

print ('    headera = models.CharField(default=".",max_length=99,verbose_name="幾號機")')
print ('    headerb = models.CharField(default=".",max_length=99,verbose_name="噸位")')
print ('    headerc = models.CharField(default=".",max_length=99,verbose_name="人員")')
print ('    headerd = models.CharField(default=".",max_length=99,verbose_name="日期")')
# print ('headere = models.CharField(default=".",max_length=99,verbose_name="備註說明")')
    


items=['格林柱','機架底座',	'模板(定)',	'模板(動)',	'合模',	'曲軸',	'鋼帶',
	'膜厚調節','壓射系統',	'澆注系統',	'油管',	'過濾網',	'油箱',	'馬達',
	'電磁閥','潤滑系統',	'氮氣',	'電路控制',	'自動噴霧',	'自動取出',	'模具'
	]
	
id=0	
for item in items:
    id+=1
    # print ({:0>2d}.format(id)+item)
    if (id<10):
        s='0'+str(id)
    else:
        s=''+str(id)
    core='    data'+s    
    print (core+'a = models.CharField(default=".",max_length=99,verbose_name="'+item+'-零件")')
    print (core+'b = models.CharField(default=".",max_length=99,verbose_name="'+item+'-進度一")')
    print (core+'c = models.CharField(default=".",max_length=99,verbose_name="'+item+'-進度二")')
    print (core+'d = models.CharField(default=".",max_length=99,verbose_name="'+item+'-進度三")')
    print (core+'e = models.CharField(default=".",max_length=99,verbose_name="'+item+'-備註說明")')
    
    
