# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0028_auto_20160818_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item004v2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.IntegerField(default=0)),
                ('field1', models.CharField(default='.', max_length=200, verbose_name='客戶')),
                ('field2', models.CharField(default='.', max_length=200, verbose_name='量產訂單號')),
                ('field3', models.CharField(default='.', max_length=200, verbose_name='產品代碼')),
                ('field4', models.CharField(default='.', max_length=200, verbose_name='產品名稱')),
                ('field5', models.CharField(default='.', max_length=200, verbose_name='計畫交期')),
                ('field6', models.CharField(default='.', max_length=200, verbose_name='訂單數量')),
                ('field7', models.CharField(default='.', max_length=200, verbose_name='實際出貨數')),
                ('field8', models.CharField(default='.', max_length=200, verbose_name='延交數量')),
            ],
        ),
    ]
