# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0033_auto_20160823_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item004',
            name='f05',
            field=models.DateField(verbose_name='計劃交期'),
        ),
    ]
