# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0040_auto_20160824_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item005',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f01', models.CharField(default='.', max_length=99, verbose_name='客戶')),
                ('f02', models.CharField(default='.', max_length=99, verbose_name='量產訂單號')),
                ('f03', models.CharField(default='.', max_length=99, verbose_name='產品代碼')),
                ('f04', models.CharField(default='.', max_length=99, verbose_name='產品名稱')),
                ('f05', models.DateField(null=True, verbose_name='計劃交期')),
                ('f06', models.IntegerField(default=0, verbose_name='訂單量')),
                ('f07', models.IntegerField(default=0, verbose_name='已交量')),
                ('f08', models.IntegerField(default=0, verbose_name='未交量')),
                ('f10', models.IntegerField(default=0, verbose_name='欠備庫量')),
                ('stat1', models.CharField(default='.', max_length=99, verbose_name='進度一')),
                ('stat2', models.CharField(default='.', max_length=99, verbose_name='進度二')),
                ('stat3', models.CharField(default='.', max_length=99, verbose_name='進度三')),
            ],
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data01e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('磨損', '磨損'), ('無法修復', '無法修復')], default='.', max_length=99, verbose_name='格林柱-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data02e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('磨損', '磨損'), ('裂縫', '裂縫'), ('磨損、裂縫', '磨損、裂縫')], default='.', max_length=99, verbose_name='機架底座-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data03e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('平面變型', '平面變型'), ('無法修復', '無法修復')], default='.', max_length=99, verbose_name='模板(定)-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data04e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('平面變型', '平面變型'), ('無法修復', '無法修復')], default='.', max_length=99, verbose_name='模板(動)-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data05e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('合模缸漏油', '合模缸漏油'), ('合模缸螺旋斷裂', '合模缸螺旋斷裂'), ('合模活塞磨損', '合模活塞磨損'), ('無法修復', '無法修復')], default='.', max_length=99, verbose_name='合模-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data06e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('磨損', '磨損'), ('無法修復', '無法修復')], default='.', max_length=99, verbose_name='曲軸-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data07e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('磨損', '磨損'), ('斷裂', '斷裂'), ('無法修復', '無法修復')], default='.', max_length=99, verbose_name='鋼帶-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data08e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('開關損壞', '開關損壞'), ('線路不通', '線路不通'), ('無法修復', '無法修復')], default='.', max_length=99, verbose_name='膜厚調節-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data09e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('無壓力', '無壓力'), ('線路不通', '線路不通'), ('壓射缸漏油', '壓射缸漏油'), ('射杆彎曲', '射杆彎曲')], default='.', max_length=99, verbose_name='壓射系統-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data10e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('斷線', '斷線'), ('短路', '短路'), ('鏈條斷', '鏈條斷'), ('編碼器異常', '編碼器異常'), ('銅套磨損', '銅套磨損')], default='.', max_length=99, verbose_name='澆注系統-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data11e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('磨損', '磨損'), ('斷裂', '斷裂'), ('接頭滑絲', '接頭滑絲')], default='.', max_length=99, verbose_name='油管-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data12e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('破損', '破損'), ('堵塞', '堵塞')], default='.', max_length=99, verbose_name='過濾網-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data13e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('油品變質', '油品變質')], default='.', max_length=99, verbose_name='油箱-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data14e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('磨損', '磨損'), ('軸心斷裂', '軸心斷裂')], default='.', max_length=99, verbose_name='馬達-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data15e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('線路不通', '線路不通'), ('閥心斷裂', '閥心斷裂')], default='.', max_length=99, verbose_name='電磁閥-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data16e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('管道不通', '管道不通'), ('管道斷裂', '管道斷裂'), ('泵心磨損', '泵心磨損')], default='.', max_length=99, verbose_name='潤滑系統-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data17e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('鋼瓶裂縫', '鋼瓶裂縫'), ('壓力過高', '壓力過高'), ('壓力過低', '壓力過低')], default='.', max_length=99, verbose_name='氮氣-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data18e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('線路不通', '線路不通'), ('短路', '短路')], default='.', max_length=99, verbose_name='電路控制-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data19e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('霧化器損壞', '霧化器損壞'), ('線路不通', '線路不通'), ('緩衝彈簧斷裂', '緩衝彈簧斷裂')], default='.', max_length=99, verbose_name='自動噴霧-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data20e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('開關損壞', '開關損壞'), ('軸承磨損', '軸承磨損'), ('緩衝器斷裂', '緩衝器斷裂'), ('線路不通', '線路不通'), ('編碼器異常', '編碼器異常')], default='.', max_length=99, verbose_name='自動取出-備註說明'),
        ),
        migrations.AlterField(
            model_name='item003v2',
            name='data21e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('尺寸NG', '尺寸NG'), ('模崩', '模崩'), ('模芯斷', '模芯斷'), ('重覆修模', '重覆修模'), ('待修模', '待修模')], default='.', max_length=99, verbose_name='模具-備註說明'),
        ),
    ]
