# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0041_auto_20160825_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='item005',
            name='f04a',
            field=models.CharField(default='.', max_length=99, verbose_name='單件品名'),
        ),
        migrations.AddField(
            model_name='item005',
            name='f04b',
            field=models.CharField(default='.', max_length=99, verbose_name='機台噸位'),
        ),
    ]
