# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0042_auto_20160825_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item006',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f01', models.CharField(default='.', max_length=99, verbose_name='客戶')),
                ('f02', models.CharField(default='.', max_length=99, verbose_name='量產訂單號')),
                ('f03', models.CharField(default='.', max_length=99, verbose_name='產品代碼')),
                ('f04', models.CharField(default='.', max_length=99, verbose_name='產品名稱')),
                ('f04a', models.CharField(default='.', max_length=99, verbose_name='單件品名')),
                ('f04b', models.CharField(default='.', max_length=99, verbose_name='機台噸位')),
                ('f05', models.DateField(null=True, verbose_name='計劃交期')),
                ('f06', models.IntegerField(default=0, verbose_name='訂單量')),
                ('f07', models.IntegerField(default=0, verbose_name='已交量')),
                ('f08', models.IntegerField(default=0, verbose_name='未交量')),
                ('f10', models.IntegerField(default=0, verbose_name='欠備庫量')),
                ('stat1', models.CharField(default='.', max_length=99, verbose_name='進度一')),
                ('stat2', models.CharField(default='.', max_length=99, verbose_name='進度二')),
                ('stat3', models.CharField(default='.', max_length=99, verbose_name='進度三')),
            ],
        ),
    ]
