# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0047_auto_20160826_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item008',
            name='data01a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data01e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data02a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data03a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data04a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data06a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data07a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data09a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data11a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data17a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data21a',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data21b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data21c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data21d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data21e',
        ),
        migrations.AddField(
            model_name='item008',
            name='data01a_01',
            field=models.NullBooleanField(verbose_name='外部主件 格林柱 零件  格林柱'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data02a_01',
            field=models.NullBooleanField(verbose_name=' 機架底座 零件  機架底座'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data02e_01',
            field=models.NullBooleanField(verbose_name=' 機架底座 備註說明  磨損'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data02e_02',
            field=models.NullBooleanField(verbose_name=' 機架底座 備註說明  裂縫'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data02e_03',
            field=models.NullBooleanField(verbose_name=' 機架底座 備註說明  漏油'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data03a_01',
            field=models.NullBooleanField(verbose_name=' 模板(定) 零件  模板(定)'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data03e_01',
            field=models.NullBooleanField(verbose_name=' 模板(定) 備註說明  平面變型'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data03e_02',
            field=models.NullBooleanField(verbose_name=' 模板(定) 備註說明  無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data04a_01',
            field=models.NullBooleanField(verbose_name=' 模板(動) 零件  模板(動)'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data04e_01',
            field=models.NullBooleanField(verbose_name=' 模板(動) 備註說明  平面變型'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data04e_02',
            field=models.NullBooleanField(verbose_name=' 模板(動) 備註說明  無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data05a_01',
            field=models.NullBooleanField(verbose_name=' 合模 零件  合模'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data05a_02',
            field=models.NullBooleanField(verbose_name=' 合模 零件  合模'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data05a_03',
            field=models.NullBooleanField(verbose_name=' 合模 零件  合模'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data05e_01',
            field=models.NullBooleanField(verbose_name=' 合模 備註說明  合模缸漏油'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data05e_02',
            field=models.NullBooleanField(verbose_name=' 合模 備註說明  合模缸螺旋斷裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data05e_03',
            field=models.NullBooleanField(verbose_name=' 合模 備註說明  合模活塞磨損'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data05e_04',
            field=models.NullBooleanField(verbose_name=' 合模 備註說明  無法修 復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data06a_01',
            field=models.NullBooleanField(verbose_name=' 曲軸 零件  曲軸'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data06a_02',
            field=models.NullBooleanField(verbose_name=' 曲軸 零件  曲軸'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data06a_03',
            field=models.NullBooleanField(verbose_name=' 曲軸 零件  曲軸'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data06e_01',
            field=models.NullBooleanField(verbose_name=' 曲軸 備註說明  磨損'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data06e_02',
            field=models.NullBooleanField(verbose_name=' 曲軸 備註說明  無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data07a_01',
            field=models.NullBooleanField(verbose_name=' 鋼帶 零件  鋼帶'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data07e_01',
            field=models.NullBooleanField(verbose_name=' 鋼帶 備註說明  磨損'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data07e_02',
            field=models.NullBooleanField(verbose_name=' 鋼帶 備註說明  斷裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data07e_03',
            field=models.NullBooleanField(verbose_name=' 鋼帶 備註說明  無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08a_01',
            field=models.NullBooleanField(verbose_name=' 保温炉 零件  保温炉'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08a_02',
            field=models.NullBooleanField(verbose_name=' 保温炉 零件  保温炉'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08a_03',
            field=models.NullBooleanField(verbose_name=' 保温炉 零件  保温炉'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08a_04',
            field=models.NullBooleanField(verbose_name=' 保温炉 零件  保温炉'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08e_01',
            field=models.NullBooleanField(verbose_name=' 保温炉 備註說明  磨損'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08e_02',
            field=models.NullBooleanField(verbose_name=' 保温炉 備註說明  斷裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08e_03',
            field=models.NullBooleanField(verbose_name=' 保温炉 備註說明  無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08e_04',
            field=models.NullBooleanField(verbose_name=' 保温炉 備註說明  炉盖损坏'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08e_05',
            field=models.NullBooleanField(verbose_name=' 保温炉 備註說明  加热管断'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08e_06',
            field=models.NullBooleanField(verbose_name=' 保温炉 備註說明  电路断'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08e_07',
            field=models.NullBooleanField(verbose_name=' 保温炉 備註說明  温度不准'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data09a_01',
            field=models.NullBooleanField(verbose_name='控制系统 膜厚調節 零件  膜厚調節'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data09e_01',
            field=models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明  開關損壞'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data09e_02',
            field=models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明  線路不通'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data09e_03',
            field=models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明  短路'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data09e_04',
            field=models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明  無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data10a_01',
            field=models.NullBooleanField(verbose_name=' 主电箱 零件  主电箱'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data10a_02',
            field=models.NullBooleanField(verbose_name=' 主电箱 零件  主电箱'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data10a_03',
            field=models.NullBooleanField(verbose_name=' 主电箱 零件  主电箱'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data10a_04',
            field=models.NullBooleanField(verbose_name=' 主电箱 零件  主电箱'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data10a_05',
            field=models.NullBooleanField(verbose_name=' 主电箱 零件  主电箱'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data10e_01',
            field=models.NullBooleanField(verbose_name=' 主电箱 備註說明  保险丝烧坏'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data10e_02',
            field=models.NullBooleanField(verbose_name=' 主电箱 備註說明  線路不通'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data10e_03',
            field=models.NullBooleanField(verbose_name=' 主电箱 備註說明  無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data11a_01',
            field=models.NullBooleanField(verbose_name=' 操作面板 零件  操作面板'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data11e_01',
            field=models.NullBooleanField(verbose_name=' 操作面板 備註說明  按键损坏'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data11e_02',
            field=models.NullBooleanField(verbose_name=' 操作面板 備註說明  系统坏'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data11e_03',
            field=models.NullBooleanField(verbose_name=' 操作面板 備註說明  無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12a_01',
            field=models.NullBooleanField(verbose_name='压射系统  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12a_02',
            field=models.NullBooleanField(verbose_name='压射系统  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12a_03',
            field=models.NullBooleanField(verbose_name='压射系统  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12a_04',
            field=models.NullBooleanField(verbose_name='压射系统  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12e_01',
            field=models.NullBooleanField(verbose_name='压射系统  備註說明  無壓力'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12e_02',
            field=models.NullBooleanField(verbose_name='压射系统  備註說明  線路不通'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12e_03',
            field=models.NullBooleanField(verbose_name='压射系统  備註說明  壓射缸漏油'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12e_04',
            field=models.NullBooleanField(verbose_name='压射系统  備註說明  射杆彎曲'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12e_05',
            field=models.NullBooleanField(verbose_name='压射系统  備註說明  连接板断裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12e_06',
            field=models.NullBooleanField(verbose_name='压射系统  備註說明  开关无信号'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12e_07',
            field=models.NullBooleanField(verbose_name='压射系统  備註說明  料管磨损'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12e_08',
            field=models.NullBooleanField(verbose_name='压射系统  備註說明  接头断'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data13a_01',
            field=models.NullBooleanField(verbose_name='澆注系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data13a_02',
            field=models.NullBooleanField(verbose_name='澆注系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data13a_03',
            field=models.NullBooleanField(verbose_name='澆注系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data13a_04',
            field=models.NullBooleanField(verbose_name='澆注系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data13a_05',
            field=models.NullBooleanField(verbose_name='澆注系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data13e_01',
            field=models.NullBooleanField(verbose_name='澆注系統  備註說明  链条断'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data13e_02',
            field=models.NullBooleanField(verbose_name='澆注系統  備註說明  齿轮滑牙斷'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data13e_03',
            field=models.NullBooleanField(verbose_name='澆注系統  備註說明  編碼器異常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data13e_04',
            field=models.NullBooleanField(verbose_name='澆注系統  備註說明  銅套磨損'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14a_01',
            field=models.NullBooleanField(verbose_name='油壓系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14a_02',
            field=models.NullBooleanField(verbose_name='油壓系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14a_03',
            field=models.NullBooleanField(verbose_name='油壓系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14a_04',
            field=models.NullBooleanField(verbose_name='油壓系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14a_05',
            field=models.NullBooleanField(verbose_name='油壓系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14e_01',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明  破損'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14e_02',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明  斷裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14e_03',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明  接頭滑絲'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14e_04',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明  堵塞'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14e_05',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明  油品變質'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14e_06',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明  磨損'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14e_07',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明  軸心斷裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14e_08',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明  線路不通'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14e_09',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明  閥心斷裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data15a_01',
            field=models.NullBooleanField(verbose_name='潤滑系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data15a_02',
            field=models.NullBooleanField(verbose_name='潤滑系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data15a_03',
            field=models.NullBooleanField(verbose_name='潤滑系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data15a_04',
            field=models.NullBooleanField(verbose_name='潤滑系統  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data15e_01',
            field=models.NullBooleanField(verbose_name='潤滑系統  備註說明  管道不通'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data15e_02',
            field=models.NullBooleanField(verbose_name='潤滑系統  備註說明  管 道斷裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data15e_03',
            field=models.NullBooleanField(verbose_name='潤滑系統  備註說明  泵心磨損'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data16a_01',
            field=models.NullBooleanField(verbose_name='氮氣  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data16a_02',
            field=models.NullBooleanField(verbose_name='氮氣  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data16e_01',
            field=models.NullBooleanField(verbose_name='氮氣  備註說明  鋼瓶裂縫'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data16e_02',
            field=models.NullBooleanField(verbose_name='氮氣  備註說明  壓力過高'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data16e_03',
            field=models.NullBooleanField(verbose_name='氮氣  備註說明  壓力過低'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data16e_04',
            field=models.NullBooleanField(verbose_name='氮氣  備註說明  磨损'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data17a_01',
            field=models.NullBooleanField(verbose_name='锁模系统  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data17e_01',
            field=models.NullBooleanField(verbose_name='锁模系统  備註說明  读数不准'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18a_01',
            field=models.NullBooleanField(verbose_name='自動噴霧  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18a_02',
            field=models.NullBooleanField(verbose_name='自動噴霧  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18a_03',
            field=models.NullBooleanField(verbose_name='自動噴霧  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18a_04',
            field=models.NullBooleanField(verbose_name='自動噴霧  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18a_05',
            field=models.NullBooleanField(verbose_name='自動噴霧  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18e_01',
            field=models.NullBooleanField(verbose_name='自動噴霧  備註說明  霧化器損壞'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18e_02',
            field=models.NullBooleanField(verbose_name='自動噴霧  備註說明  線路不通'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18e_03',
            field=models.NullBooleanField(verbose_name='自動噴霧  備註說明  緩衝彈簧斷裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18e_04',
            field=models.NullBooleanField(verbose_name='自動噴霧  備註說明  喷头螺丝滑牙'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18e_05',
            field=models.NullBooleanField(verbose_name='自動噴霧  備註說明  断裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18e_06',
            field=models.NullBooleanField(verbose_name='自動噴霧  備註說明  漏水'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data19a_01',
            field=models.NullBooleanField(verbose_name='自動取出  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data19a_02',
            field=models.NullBooleanField(verbose_name='自動取出  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data19a_03',
            field=models.NullBooleanField(verbose_name='自動取出  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data19a_04',
            field=models.NullBooleanField(verbose_name='自動取出  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data19a_05',
            field=models.NullBooleanField(verbose_name='自動取出  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data19e_01',
            field=models.NullBooleanField(verbose_name='自動取出  備註說明  手臂断裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data19e_02',
            field=models.NullBooleanField(verbose_name='自動取出  備註說明  夹手磨损'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data19e_03',
            field=models.NullBooleanField(verbose_name='自動取出  備註說明  缓冲器坏'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data19e_04',
            field=models.NullBooleanField(verbose_name='自動取出  備註說明  手臂轴承坏'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data19e_05',
            field=models.NullBooleanField(verbose_name='自動取出  備註說明  内部烧坏'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20a_01',
            field=models.NullBooleanField(verbose_name='模具  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20a_02',
            field=models.NullBooleanField(verbose_name='模具  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20a_03',
            field=models.NullBooleanField(verbose_name='模具  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20a_04',
            field=models.NullBooleanField(verbose_name='模具  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20a_05',
            field=models.NullBooleanField(verbose_name='模具  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20a_06',
            field=models.NullBooleanField(verbose_name='模具  零件  '),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20e_01',
            field=models.NullBooleanField(verbose_name='模具  備註說明  尺寸NG'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20e_02',
            field=models.NullBooleanField(verbose_name='模具  備註說明  模崩'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20e_03',
            field=models.NullBooleanField(verbose_name='模具  備註說明  模芯斷'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20e_04',
            field=models.NullBooleanField(verbose_name='模具  備註說明  顶针斷'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20e_05',
            field=models.NullBooleanField(verbose_name='模具  備註說明  重覆修模'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20e_06',
            field=models.NullBooleanField(verbose_name='模具  備註說明  待修模'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data01b',
            field=models.CharField(default='.', max_length=99, verbose_name='外部主件 格林柱 進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data01c',
            field=models.CharField(default='.', max_length=99, verbose_name='外部主件 格林柱 進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data01d',
            field=models.CharField(default='.', max_length=99, verbose_name='外部主件 格林柱 進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data01e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name='外部主件 格林柱 備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data01e_01',
            field=models.NullBooleanField(verbose_name='外部主件 格林柱 備註說明  磨損'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data01e_02',
            field=models.NullBooleanField(verbose_name='外部主件 格林柱 備註說明  無法修復'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data02b',
            field=models.CharField(default='.', max_length=99, verbose_name=' 機架底座 進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data02c',
            field=models.CharField(default='.', max_length=99, verbose_name=' 機架底座 進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data02d',
            field=models.CharField(default='.', max_length=99, verbose_name=' 機架底座 進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data02e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name=' 機架底座 備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data03b',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(定) 進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data03c',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(定) 進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data03d',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(定) 進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data03e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name=' 模板(定) 備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data04b',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(動) 進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data04c',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(動) 進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data04d',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(動) 進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data04e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name=' 模板(動) 備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data05b',
            field=models.CharField(default='.', max_length=99, verbose_name=' 合模 進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data05c',
            field=models.CharField(default='.', max_length=99, verbose_name=' 合模 進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data05d',
            field=models.CharField(default='.', max_length=99, verbose_name=' 合模 進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data05e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name=' 合模 備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data06b',
            field=models.CharField(default='.', max_length=99, verbose_name=' 曲軸 進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data06c',
            field=models.CharField(default='.', max_length=99, verbose_name=' 曲軸 進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data06d',
            field=models.CharField(default='.', max_length=99, verbose_name=' 曲軸 進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data06e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name=' 曲軸 備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data07b',
            field=models.CharField(default='.', max_length=99, verbose_name=' 鋼帶 進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data07c',
            field=models.CharField(default='.', max_length=99, verbose_name=' 鋼帶 進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data07d',
            field=models.CharField(default='.', max_length=99, verbose_name=' 鋼帶 進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data07e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name=' 鋼帶 備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data08b',
            field=models.CharField(default='.', max_length=99, verbose_name=' 保温炉 進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data08c',
            field=models.CharField(default='.', max_length=99, verbose_name=' 保温炉 進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data08d',
            field=models.CharField(default='.', max_length=99, verbose_name=' 保温炉 進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data08e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name=' 保温炉 備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data09b',
            field=models.CharField(default='.', max_length=99, verbose_name='控制系统 膜厚調節 進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data09c',
            field=models.CharField(default='.', max_length=99, verbose_name='控制系统 膜厚調節 進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data09d',
            field=models.CharField(default='.', max_length=99, verbose_name='控制系统 膜厚調節 進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data09e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name='控制系统 膜厚調節 備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data10b',
            field=models.CharField(default='.', max_length=99, verbose_name=' 主电箱 進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data10c',
            field=models.CharField(default='.', max_length=99, verbose_name=' 主电箱 進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data10d',
            field=models.CharField(default='.', max_length=99, verbose_name=' 主电箱 進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data10e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name=' 主电箱 備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data11b',
            field=models.CharField(default='.', max_length=99, verbose_name=' 操作面板 進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data11c',
            field=models.CharField(default='.', max_length=99, verbose_name=' 操作面板 進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data11d',
            field=models.CharField(default='.', max_length=99, verbose_name=' 操作面板 進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data11e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name=' 操作面板 備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data12b',
            field=models.CharField(default='.', max_length=99, verbose_name='压射系统  進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data12c',
            field=models.CharField(default='.', max_length=99, verbose_name='压射系统  進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data12d',
            field=models.CharField(default='.', max_length=99, verbose_name='压射系统  進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data12e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name='压射系统  備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data13b',
            field=models.CharField(default='.', max_length=99, verbose_name='澆注系統  進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data13c',
            field=models.CharField(default='.', max_length=99, verbose_name='澆注系統  進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data13d',
            field=models.CharField(default='.', max_length=99, verbose_name='澆注系統  進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data13e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name='澆注系統  備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data14b',
            field=models.CharField(default='.', max_length=99, verbose_name='油壓系統  進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data14c',
            field=models.CharField(default='.', max_length=99, verbose_name='油壓系統  進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data14d',
            field=models.CharField(default='.', max_length=99, verbose_name='油壓系統  進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data14e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name='油壓系統  備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data15b',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑系統  進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data15c',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑系統  進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data15d',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑系統  進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data15e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name='潤滑系統  備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data16b',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣  進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data16c',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣  進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data16d',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣  進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data16e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name='氮氣  備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data17b',
            field=models.CharField(default='.', max_length=99, verbose_name='锁模系统  進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data17c',
            field=models.CharField(default='.', max_length=99, verbose_name='锁模系统  進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data17d',
            field=models.CharField(default='.', max_length=99, verbose_name='锁模系统  進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data17e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name='锁模系统  備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data18b',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧  進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data18c',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧  進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data18d',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧  進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data18e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name='自動噴霧  備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data19b',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出  進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data19c',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出  進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data19d',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出  進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data19e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name='自動取出  備註說明'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data20b',
            field=models.CharField(default='.', max_length=99, verbose_name='模具  進度一'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data20c',
            field=models.CharField(default='.', max_length=99, verbose_name='模具  進度二'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data20d',
            field=models.CharField(default='.', max_length=99, verbose_name='模具  進度三'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='data20e',
            field=models.CharField(choices=[('---', '---'), ('正常', '正常'), ('不正常', '不正常')], default='.', max_length=99, verbose_name='模具  備註說明'),
        ),
    ]
