# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0048_auto_20160826_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item008',
            name='data01e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data02e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data03e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data04e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data06e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data07e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data09e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data11e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data17e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19e',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20e',
        ),
        migrations.AddField(
            model_name='item008',
            name='data01e_00',
            field=models.NullBooleanField(verbose_name='外部主件 格林柱 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data02e_00',
            field=models.NullBooleanField(verbose_name=' 機架底座 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data03e_00',
            field=models.NullBooleanField(verbose_name=' 模板(定) 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data04e_00',
            field=models.NullBooleanField(verbose_name=' 模板(動) 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data05e_00',
            field=models.NullBooleanField(verbose_name=' 合模 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data06e_00',
            field=models.NullBooleanField(verbose_name=' 曲軸 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data07e_00',
            field=models.NullBooleanField(verbose_name=' 鋼帶 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data08e_00',
            field=models.NullBooleanField(verbose_name=' 保温炉 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data09e_00',
            field=models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data10e_00',
            field=models.NullBooleanField(verbose_name=' 主电箱 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data11e_00',
            field=models.NullBooleanField(verbose_name=' 操作面板 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data12e_00',
            field=models.NullBooleanField(verbose_name='压射系统  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data13e_00',
            field=models.NullBooleanField(verbose_name='澆注系統  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data14e_00',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data15e_00',
            field=models.NullBooleanField(verbose_name='潤滑系統  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data16e_00',
            field=models.NullBooleanField(verbose_name='氮氣  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data17e_00',
            field=models.NullBooleanField(verbose_name='锁模系统  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data18e_00',
            field=models.NullBooleanField(verbose_name='自動噴霧  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data19e_00',
            field=models.NullBooleanField(verbose_name='自動取出  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='data20e_00',
            field=models.NullBooleanField(verbose_name='模具  備註說明  正常'),
        ),
    ]
