# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0049_auto_20160826_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item009',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headera', models.CharField(default='.', max_length=99, verbose_name='幾號機')),
                ('headerb', models.CharField(default='.', max_length=99, verbose_name='噸位')),
                ('headerc', models.CharField(default='.', max_length=99, verbose_name='人員')),
                ('headerd', models.DateField(verbose_name='日期')),
                ('data01a_01', models.NullBooleanField(verbose_name='外部主件 格林柱 零件  格林柱')),
                ('data01b', models.CharField(default='.', max_length=99, verbose_name='外部主件 格林柱 進度一')),
                ('data01c', models.CharField(default='.', max_length=99, verbose_name='外部主件 格林柱 進度二')),
                ('data01d', models.CharField(default='.', max_length=99, verbose_name='外部主件 格林柱 進度三')),
                ('data01e_00', models.NullBooleanField(verbose_name='外部主件 格林柱 備註說明  正常')),
                ('data01e_01', models.NullBooleanField(verbose_name='外部主件 格林柱 備註說明  磨損')),
                ('data01e_02', models.NullBooleanField(verbose_name='外部主件 格林柱 備註說明  無法修復')),
                ('data02a_01', models.NullBooleanField(verbose_name=' 機架底座 零件  機架底座')),
                ('data02b', models.CharField(default='.', max_length=99, verbose_name=' 機架底座 進度一')),
                ('data02c', models.CharField(default='.', max_length=99, verbose_name=' 機架底座 進度二')),
                ('data02d', models.CharField(default='.', max_length=99, verbose_name=' 機架底座 進度三')),
                ('data02e_00', models.NullBooleanField(verbose_name=' 機架底座 備註說明  正常')),
                ('data02e_01', models.NullBooleanField(verbose_name=' 機架底座 備註說明  磨損')),
                ('data02e_02', models.NullBooleanField(verbose_name=' 機架底座 備註說明  裂縫')),
                ('data02e_03', models.NullBooleanField(verbose_name=' 機架底座 備註說明  漏油')),
                ('data03a_01', models.NullBooleanField(verbose_name=' 模板(定) 零件  模板(定)')),
                ('data03b', models.CharField(default='.', max_length=99, verbose_name=' 模板(定) 進度一')),
                ('data03c', models.CharField(default='.', max_length=99, verbose_name=' 模板(定) 進度二')),
                ('data03d', models.CharField(default='.', max_length=99, verbose_name=' 模板(定) 進度三')),
                ('data03e_00', models.NullBooleanField(verbose_name=' 模板(定) 備註說明  正常')),
                ('data03e_01', models.NullBooleanField(verbose_name=' 模板(定) 備註說明  平面變型')),
                ('data03e_02', models.NullBooleanField(verbose_name=' 模板(定) 備註說明  無法修復')),
                ('data04a_01', models.NullBooleanField(verbose_name=' 模板(動) 零件  模板(動)')),
                ('data04b', models.CharField(default='.', max_length=99, verbose_name=' 模板(動) 進度一')),
                ('data04c', models.CharField(default='.', max_length=99, verbose_name=' 模板(動) 進度二')),
                ('data04d', models.CharField(default='.', max_length=99, verbose_name=' 模板(動) 進度三')),
                ('data04e_00', models.NullBooleanField(verbose_name=' 模板(動) 備註說明  正常')),
                ('data04e_01', models.NullBooleanField(verbose_name=' 模板(動) 備註說明  平面變型')),
                ('data04e_02', models.NullBooleanField(verbose_name=' 模板(動) 備註說明  無法修復')),
                ('data05a_01', models.NullBooleanField(verbose_name=' 合模 零件  合模')),
                ('data05a_02', models.NullBooleanField(verbose_name=' 合模 零件  合模')),
                ('data05a_03', models.NullBooleanField(verbose_name=' 合模 零件  合模')),
                ('data05b', models.CharField(default='.', max_length=99, verbose_name=' 合模 進度一')),
                ('data05c', models.CharField(default='.', max_length=99, verbose_name=' 合模 進度二')),
                ('data05d', models.CharField(default='.', max_length=99, verbose_name=' 合模 進度三')),
                ('data05e_00', models.NullBooleanField(verbose_name=' 合模 備註說明  正常')),
                ('data05e_01', models.NullBooleanField(verbose_name=' 合模 備註說明  合模缸漏油')),
                ('data05e_02', models.NullBooleanField(verbose_name=' 合模 備註說明  合模缸螺旋斷裂')),
                ('data05e_03', models.NullBooleanField(verbose_name=' 合模 備註說明  合模活塞磨損')),
                ('data05e_04', models.NullBooleanField(verbose_name=' 合模 備註說明  無法修 復')),
                ('data06a_01', models.NullBooleanField(verbose_name=' 曲軸 零件  曲軸')),
                ('data06a_02', models.NullBooleanField(verbose_name=' 曲軸 零件  曲軸')),
                ('data06a_03', models.NullBooleanField(verbose_name=' 曲軸 零件  曲軸')),
                ('data06b', models.CharField(default='.', max_length=99, verbose_name=' 曲軸 進度一')),
                ('data06c', models.CharField(default='.', max_length=99, verbose_name=' 曲軸 進度二')),
                ('data06d', models.CharField(default='.', max_length=99, verbose_name=' 曲軸 進度三')),
                ('data06e_00', models.NullBooleanField(verbose_name=' 曲軸 備註說明  正常')),
                ('data06e_01', models.NullBooleanField(verbose_name=' 曲軸 備註說明  磨損')),
                ('data06e_02', models.NullBooleanField(verbose_name=' 曲軸 備註說明  無法修復')),
                ('data07a_01', models.NullBooleanField(verbose_name=' 鋼帶 零件  鋼帶')),
                ('data07b', models.CharField(default='.', max_length=99, verbose_name=' 鋼帶 進度一')),
                ('data07c', models.CharField(default='.', max_length=99, verbose_name=' 鋼帶 進度二')),
                ('data07d', models.CharField(default='.', max_length=99, verbose_name=' 鋼帶 進度三')),
                ('data07e_00', models.NullBooleanField(verbose_name=' 鋼帶 備註說明  正常')),
                ('data07e_01', models.NullBooleanField(verbose_name=' 鋼帶 備註說明  磨損')),
                ('data07e_02', models.NullBooleanField(verbose_name=' 鋼帶 備註說明  斷裂')),
                ('data07e_03', models.NullBooleanField(verbose_name=' 鋼帶 備註說明  無法修復')),
                ('data08a_01', models.NullBooleanField(verbose_name=' 保温炉 零件  保温炉')),
                ('data08a_02', models.NullBooleanField(verbose_name=' 保温炉 零件  保温炉')),
                ('data08a_03', models.NullBooleanField(verbose_name=' 保温炉 零件  保温炉')),
                ('data08a_04', models.NullBooleanField(verbose_name=' 保温炉 零件  保温炉')),
                ('data08b', models.CharField(default='.', max_length=99, verbose_name=' 保温炉 進度一')),
                ('data08c', models.CharField(default='.', max_length=99, verbose_name=' 保温炉 進度二')),
                ('data08d', models.CharField(default='.', max_length=99, verbose_name=' 保温炉 進度三')),
                ('data08e_00', models.NullBooleanField(verbose_name=' 保温炉 備註說明  正常')),
                ('data08e_01', models.NullBooleanField(verbose_name=' 保温炉 備註說明  磨損')),
                ('data08e_02', models.NullBooleanField(verbose_name=' 保温炉 備註說明  斷裂')),
                ('data08e_03', models.NullBooleanField(verbose_name=' 保温炉 備註說明  無法修復')),
                ('data08e_04', models.NullBooleanField(verbose_name=' 保温炉 備註說明  炉盖损坏')),
                ('data08e_05', models.NullBooleanField(verbose_name=' 保温炉 備註說明  加热管断')),
                ('data08e_06', models.NullBooleanField(verbose_name=' 保温炉 備註說明  电路断')),
                ('data08e_07', models.NullBooleanField(verbose_name=' 保温炉 備註說明  温度不准')),
                ('data09a_01', models.NullBooleanField(verbose_name='控制系统 膜厚調節 零件  膜厚調節')),
                ('data09b', models.CharField(default='.', max_length=99, verbose_name='控制系统 膜厚調節 進度一')),
                ('data09c', models.CharField(default='.', max_length=99, verbose_name='控制系统 膜厚調節 進度二')),
                ('data09d', models.CharField(default='.', max_length=99, verbose_name='控制系统 膜厚調節 進度三')),
                ('data09e_00', models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明  正常')),
                ('data09e_01', models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明  開關損壞')),
                ('data09e_02', models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明  線路不通')),
                ('data09e_03', models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明  短路')),
                ('data09e_04', models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明  無法修復')),
                ('data10a_01', models.NullBooleanField(verbose_name=' 主电箱 零件  主电箱')),
                ('data10a_02', models.NullBooleanField(verbose_name=' 主电箱 零件  主电箱')),
                ('data10a_03', models.NullBooleanField(verbose_name=' 主电箱 零件  主电箱')),
                ('data10a_04', models.NullBooleanField(verbose_name=' 主电箱 零件  主电箱')),
                ('data10a_05', models.NullBooleanField(verbose_name=' 主电箱 零件  主电箱')),
                ('data10b', models.CharField(default='.', max_length=99, verbose_name=' 主电箱 進度一')),
                ('data10c', models.CharField(default='.', max_length=99, verbose_name=' 主电箱 進度二')),
                ('data10d', models.CharField(default='.', max_length=99, verbose_name=' 主电箱 進度三')),
                ('data10e_00', models.NullBooleanField(verbose_name=' 主电箱 備註說明  正常')),
                ('data10e_01', models.NullBooleanField(verbose_name=' 主电箱 備註說明  保险丝烧坏')),
                ('data10e_02', models.NullBooleanField(verbose_name=' 主电箱 備註說明  線路不通')),
                ('data10e_03', models.NullBooleanField(verbose_name=' 主电箱 備註說明  無法修復')),
                ('data11a_01', models.NullBooleanField(verbose_name=' 操作面板 零件  操作面板')),
                ('data11b', models.CharField(default='.', max_length=99, verbose_name=' 操作面板 進度一')),
                ('data11c', models.CharField(default='.', max_length=99, verbose_name=' 操作面板 進度二')),
                ('data11d', models.CharField(default='.', max_length=99, verbose_name=' 操作面板 進度三')),
                ('data11e_00', models.NullBooleanField(verbose_name=' 操作面板 備註說明  正常')),
                ('data11e_01', models.NullBooleanField(verbose_name=' 操作面板 備註說明  按键损坏')),
                ('data11e_02', models.NullBooleanField(verbose_name=' 操作面板 備註說明  系统坏')),
                ('data11e_03', models.NullBooleanField(verbose_name=' 操作面板 備註說明  無法修復')),
                ('data12a_01', models.NullBooleanField(verbose_name='压射系统  零件  ')),
                ('data12a_02', models.NullBooleanField(verbose_name='压射系统  零件  ')),
                ('data12a_03', models.NullBooleanField(verbose_name='压射系统  零件  ')),
                ('data12a_04', models.NullBooleanField(verbose_name='压射系统  零件  ')),
                ('data12b', models.CharField(default='.', max_length=99, verbose_name='压射系统  進度一')),
                ('data12c', models.CharField(default='.', max_length=99, verbose_name='压射系统  進度二')),
                ('data12d', models.CharField(default='.', max_length=99, verbose_name='压射系统  進度三')),
                ('data12e_00', models.NullBooleanField(verbose_name='压射系统  備註說明  正常')),
                ('data12e_01', models.NullBooleanField(verbose_name='压射系统  備註說明  無壓力')),
                ('data12e_02', models.NullBooleanField(verbose_name='压射系统  備註說明  線路不通')),
                ('data12e_03', models.NullBooleanField(verbose_name='压射系统  備註說明  壓射缸漏油')),
                ('data12e_04', models.NullBooleanField(verbose_name='压射系统  備註說明  射杆彎曲')),
                ('data12e_05', models.NullBooleanField(verbose_name='压射系统  備註說明  连接板断裂')),
                ('data12e_06', models.NullBooleanField(verbose_name='压射系统  備註說明  开关无信号')),
                ('data12e_07', models.NullBooleanField(verbose_name='压射系统  備註說明  料管磨损')),
                ('data12e_08', models.NullBooleanField(verbose_name='压射系统  備註說明  接头断')),
                ('data13a_01', models.NullBooleanField(verbose_name='澆注系統  零件  ')),
                ('data13a_02', models.NullBooleanField(verbose_name='澆注系統  零件  ')),
                ('data13a_03', models.NullBooleanField(verbose_name='澆注系統  零件  ')),
                ('data13a_04', models.NullBooleanField(verbose_name='澆注系統  零件  ')),
                ('data13a_05', models.NullBooleanField(verbose_name='澆注系統  零件  ')),
                ('data13b', models.CharField(default='.', max_length=99, verbose_name='澆注系統  進度一')),
                ('data13c', models.CharField(default='.', max_length=99, verbose_name='澆注系統  進度二')),
                ('data13d', models.CharField(default='.', max_length=99, verbose_name='澆注系統  進度三')),
                ('data13e_00', models.NullBooleanField(verbose_name='澆注系統  備註說明  正常')),
                ('data13e_01', models.NullBooleanField(verbose_name='澆注系統  備註說明  链条断')),
                ('data13e_02', models.NullBooleanField(verbose_name='澆注系統  備註說明  齿轮滑牙斷')),
                ('data13e_03', models.NullBooleanField(verbose_name='澆注系統  備註說明  編碼器異常')),
                ('data13e_04', models.NullBooleanField(verbose_name='澆注系統  備註說明  銅套磨損')),
                ('data14a_01', models.NullBooleanField(verbose_name='油壓系統  零件  ')),
                ('data14a_02', models.NullBooleanField(verbose_name='油壓系統  零件  ')),
                ('data14a_03', models.NullBooleanField(verbose_name='油壓系統  零件  ')),
                ('data14a_04', models.NullBooleanField(verbose_name='油壓系統  零件  ')),
                ('data14a_05', models.NullBooleanField(verbose_name='油壓系統  零件  ')),
                ('data14b', models.CharField(default='.', max_length=99, verbose_name='油壓系統  進度一')),
                ('data14c', models.CharField(default='.', max_length=99, verbose_name='油壓系統  進度二')),
                ('data14d', models.CharField(default='.', max_length=99, verbose_name='油壓系統  進度三')),
                ('data14e_00', models.NullBooleanField(verbose_name='油壓系統  備註說明  正常')),
                ('data14e_01', models.NullBooleanField(verbose_name='油壓系統  備註說明  破損')),
                ('data14e_02', models.NullBooleanField(verbose_name='油壓系統  備註說明  斷裂')),
                ('data14e_03', models.NullBooleanField(verbose_name='油壓系統  備註說明  接頭滑絲')),
                ('data14e_04', models.NullBooleanField(verbose_name='油壓系統  備註說明  堵塞')),
                ('data14e_05', models.NullBooleanField(verbose_name='油壓系統  備註說明  油品變質')),
                ('data14e_06', models.NullBooleanField(verbose_name='油壓系統  備註說明  磨損')),
                ('data14e_07', models.NullBooleanField(verbose_name='油壓系統  備註說明  軸心斷裂')),
                ('data14e_08', models.NullBooleanField(verbose_name='油壓系統  備註說明  線路不通')),
                ('data14e_09', models.NullBooleanField(verbose_name='油壓系統  備註說明  閥心斷裂')),
                ('data15a_01', models.NullBooleanField(verbose_name='潤滑系統  零件  ')),
                ('data15a_02', models.NullBooleanField(verbose_name='潤滑系統  零件  ')),
                ('data15a_03', models.NullBooleanField(verbose_name='潤滑系統  零件  ')),
                ('data15a_04', models.NullBooleanField(verbose_name='潤滑系統  零件  ')),
                ('data15b', models.CharField(default='.', max_length=99, verbose_name='潤滑系統  進度一')),
                ('data15c', models.CharField(default='.', max_length=99, verbose_name='潤滑系統  進度二')),
                ('data15d', models.CharField(default='.', max_length=99, verbose_name='潤滑系統  進度三')),
                ('data15e_00', models.NullBooleanField(verbose_name='潤滑系統  備註說明  正常')),
                ('data15e_01', models.NullBooleanField(verbose_name='潤滑系統  備註說明  管道不通')),
                ('data15e_02', models.NullBooleanField(verbose_name='潤滑系統  備註說明  管 道斷裂')),
                ('data15e_03', models.NullBooleanField(verbose_name='潤滑系統  備註說明  泵心磨損')),
                ('data16a_01', models.NullBooleanField(verbose_name='氮氣  零件  ')),
                ('data16a_02', models.NullBooleanField(verbose_name='氮氣  零件  ')),
                ('data16b', models.CharField(default='.', max_length=99, verbose_name='氮氣  進度一')),
                ('data16c', models.CharField(default='.', max_length=99, verbose_name='氮氣  進度二')),
                ('data16d', models.CharField(default='.', max_length=99, verbose_name='氮氣  進度三')),
                ('data16e_00', models.NullBooleanField(verbose_name='氮氣  備註說明  正常')),
                ('data16e_01', models.NullBooleanField(verbose_name='氮氣  備註說明  鋼瓶裂縫')),
                ('data16e_02', models.NullBooleanField(verbose_name='氮氣  備註說明  壓力過高')),
                ('data16e_03', models.NullBooleanField(verbose_name='氮氣  備註說明  壓力過低')),
                ('data16e_04', models.NullBooleanField(verbose_name='氮氣  備註說明  磨损')),
                ('data17a_01', models.NullBooleanField(verbose_name='锁模系统  零件  ')),
                ('data17b', models.CharField(default='.', max_length=99, verbose_name='锁模系统  進度一')),
                ('data17c', models.CharField(default='.', max_length=99, verbose_name='锁模系统  進度二')),
                ('data17d', models.CharField(default='.', max_length=99, verbose_name='锁模系统  進度三')),
                ('data17e_00', models.NullBooleanField(verbose_name='锁模系统  備註說明  正常')),
                ('data17e_01', models.NullBooleanField(verbose_name='锁模系统  備註說明  读数不准')),
                ('data18a_01', models.NullBooleanField(verbose_name='自動噴霧  零件  ')),
                ('data18a_02', models.NullBooleanField(verbose_name='自動噴霧  零件  ')),
                ('data18a_03', models.NullBooleanField(verbose_name='自動噴霧  零件  ')),
                ('data18a_04', models.NullBooleanField(verbose_name='自動噴霧  零件  ')),
                ('data18a_05', models.NullBooleanField(verbose_name='自動噴霧  零件  ')),
                ('data18b', models.CharField(default='.', max_length=99, verbose_name='自動噴霧  進度一')),
                ('data18c', models.CharField(default='.', max_length=99, verbose_name='自動噴霧  進度二')),
                ('data18d', models.CharField(default='.', max_length=99, verbose_name='自動噴霧  進度三')),
                ('data18e_00', models.NullBooleanField(verbose_name='自動噴霧  備註說明  正常')),
                ('data18e_01', models.NullBooleanField(verbose_name='自動噴霧  備註說明  霧化器損壞')),
                ('data18e_02', models.NullBooleanField(verbose_name='自動噴霧  備註說明  線路不通')),
                ('data18e_03', models.NullBooleanField(verbose_name='自動噴霧  備註說明  緩衝彈簧斷裂')),
                ('data18e_04', models.NullBooleanField(verbose_name='自動噴霧  備註說明  喷头螺丝滑牙')),
                ('data18e_05', models.NullBooleanField(verbose_name='自動噴霧  備註說明  断裂')),
                ('data18e_06', models.NullBooleanField(verbose_name='自動噴霧  備註說明  漏水')),
                ('data19a_01', models.NullBooleanField(verbose_name='自動取出  零件  ')),
                ('data19a_02', models.NullBooleanField(verbose_name='自動取出  零件  ')),
                ('data19a_03', models.NullBooleanField(verbose_name='自動取出  零件  ')),
                ('data19a_04', models.NullBooleanField(verbose_name='自動取出  零件  ')),
                ('data19a_05', models.NullBooleanField(verbose_name='自動取出  零件  ')),
                ('data19b', models.CharField(default='.', max_length=99, verbose_name='自動取出  進度一')),
                ('data19c', models.CharField(default='.', max_length=99, verbose_name='自動取出  進度二')),
                ('data19d', models.CharField(default='.', max_length=99, verbose_name='自動取出  進度三')),
                ('data19e_00', models.NullBooleanField(verbose_name='自動取出  備註說明  正常')),
                ('data19e_01', models.NullBooleanField(verbose_name='自動取出  備註說明  手臂断裂')),
                ('data19e_02', models.NullBooleanField(verbose_name='自動取出  備註說明  夹手磨损')),
                ('data19e_03', models.NullBooleanField(verbose_name='自動取出  備註說明  缓冲器坏')),
                ('data19e_04', models.NullBooleanField(verbose_name='自動取出  備註說明  手臂轴承坏')),
                ('data19e_05', models.NullBooleanField(verbose_name='自動取出  備註說明  内部烧坏')),
                ('data20a_01', models.NullBooleanField(verbose_name='模具  零件  ')),
                ('data20a_02', models.NullBooleanField(verbose_name='模具  零件  ')),
                ('data20a_03', models.NullBooleanField(verbose_name='模具  零件  ')),
                ('data20a_04', models.NullBooleanField(verbose_name='模具  零件  ')),
                ('data20a_05', models.NullBooleanField(verbose_name='模具  零件  ')),
                ('data20a_06', models.NullBooleanField(verbose_name='模具  零件  ')),
                ('data20b', models.CharField(default='.', max_length=99, verbose_name='模具  進度一')),
                ('data20c', models.CharField(default='.', max_length=99, verbose_name='模具  進度二')),
                ('data20d', models.CharField(default='.', max_length=99, verbose_name='模具  進度三')),
                ('data20e_00', models.NullBooleanField(verbose_name='模具  備註說明  正常')),
                ('data20e_01', models.NullBooleanField(verbose_name='模具  備註說明  尺寸NG')),
                ('data20e_02', models.NullBooleanField(verbose_name='模具  備註說明  模崩')),
                ('data20e_03', models.NullBooleanField(verbose_name='模具  備註說明  模芯斷')),
                ('data20e_04', models.NullBooleanField(verbose_name='模具  備註說明  顶针斷')),
                ('data20e_05', models.NullBooleanField(verbose_name='模具  備註說明  重覆修模')),
                ('data20e_06', models.NullBooleanField(verbose_name='模具  備註說明  待修模')),
            ],
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data01a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data01b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data01c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data01d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data01e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data01e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data01e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data02a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data02b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data02c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data02d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data02e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data02e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data02e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data02e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data03a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data03b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data03c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data03d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data03e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data03e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data03e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data04a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data04b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data04c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data04d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data04e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data04e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data04e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05a_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data05e_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data06a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data06a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data06a_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data06b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data06c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data06d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data06e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data06e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data06e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data07a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data07b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data07c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data07d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data07e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data07e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data07e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data07e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08a_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08a_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08e_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08e_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08e_06',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data08e_07',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data09a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data09b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data09c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data09d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data09e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data09e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data09e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data09e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data09e_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10a_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10a_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10a_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data10e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data11a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data11b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data11c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data11d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data11e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data11e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data11e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data11e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12a_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12a_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12e_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12e_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12e_06',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12e_07',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data12e_08',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13a_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13a_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13a_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data13e_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14a_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14a_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14a_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14e_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14e_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14e_06',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14e_07',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14e_08',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data14e_09',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15a_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15a_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data15e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data16e_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data17a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data17b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data17c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data17d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data17e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data17e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18a_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18a_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18a_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18e_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18e_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data18e_06',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19a_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19a_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19a_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19e_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data19e_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20a_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20a_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20a_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20a_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20a_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20a_06',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20b',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20c',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20d',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20e_00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20e_01',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20e_02',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20e_03',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20e_04',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20e_05',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='data20e_06',
        ),
        migrations.AddField(
            model_name='item008',
            name='row01c00',
            field=models.CharField(default='.', max_length=99, verbose_name='外部主件 格林柱 零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row01c01',
            field=models.NullBooleanField(verbose_name='外部主件 格林柱 零件 => 格林柱'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row01d00',
            field=models.CharField(default='.', max_length=99, verbose_name='外部主件 格林柱 進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row01e00',
            field=models.CharField(default='.', max_length=99, verbose_name='外部主件 格林柱 進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row01f00',
            field=models.CharField(default='.', max_length=99, verbose_name='外部主件 格林柱 進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row01g00',
            field=models.NullBooleanField(verbose_name='外部主件 格林柱 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row01g02',
            field=models.NullBooleanField(verbose_name='外部主件 格林柱 備註說明 => 無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row02c00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 機架底座 零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row02c01',
            field=models.NullBooleanField(verbose_name=' 機架底座 零件 => 機架底座'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row02d00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 機架底座 進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row02e00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 機架底座 進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row02f00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 機架底座 進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row02g00',
            field=models.NullBooleanField(verbose_name=' 機架底座 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row02g03',
            field=models.NullBooleanField(verbose_name=' 機架底座 備註說明 => 漏油'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row03c00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(定) 零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row03c01',
            field=models.NullBooleanField(verbose_name=' 模板(定) 零件 => 模板(定)'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row03d00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(定) 進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row03e00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(定) 進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row03f00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(定) 進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row03g00',
            field=models.NullBooleanField(verbose_name=' 模板(定) 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row03g02',
            field=models.NullBooleanField(verbose_name=' 模板(定) 備註說明 => 無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row04c00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(動) 零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row04c01',
            field=models.NullBooleanField(verbose_name=' 模板(動) 零件 => 模板(動)'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row04d00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(動) 進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row04e00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(動) 進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row04f00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 模板(動) 進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row04g00',
            field=models.NullBooleanField(verbose_name=' 模板(動) 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row04g02',
            field=models.NullBooleanField(verbose_name=' 模板(動) 備註說明 => 無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row05c00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 合模 零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row05c01',
            field=models.NullBooleanField(verbose_name=' 合模 零件 => 油路板'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row05c02',
            field=models.NullBooleanField(verbose_name=' 合模 零件 => 合模油缸'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row05d00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 合模 進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row05e00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 合模 進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row05f00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 合模 進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row05g00',
            field=models.NullBooleanField(verbose_name=' 合模 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row05g04',
            field=models.NullBooleanField(verbose_name=' 合模 備註說明 => 無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row06c00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 曲軸 零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row06c01',
            field=models.NullBooleanField(verbose_name=' 曲軸 零件 => 曲轴销'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row06c02',
            field=models.NullBooleanField(verbose_name=' 曲軸 零件 => 衬套'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row06d00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 曲軸 進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row06e00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 曲軸 進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row06f00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 曲軸 進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row06g00',
            field=models.NullBooleanField(verbose_name=' 曲軸 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row06g02',
            field=models.NullBooleanField(verbose_name=' 曲軸 備註說明 => 無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row07c00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 鋼帶 零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row07c01',
            field=models.NullBooleanField(verbose_name=' 鋼帶 零件 => 鋼帶'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row07d00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 鋼帶 進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row07e00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 鋼帶 進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row07f00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 鋼帶 進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row07g00',
            field=models.NullBooleanField(verbose_name=' 鋼帶 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row07g03',
            field=models.NullBooleanField(verbose_name=' 鋼帶 備註說明 => 無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row08c00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 保温炉 零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row08c01',
            field=models.NullBooleanField(verbose_name=' 保温炉 零件 => 炉盖'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row08c02',
            field=models.NullBooleanField(verbose_name=' 保温炉 零件 => 加热管'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row08c03',
            field=models.NullBooleanField(verbose_name=' 保温炉 零件 => 电线'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row08c04',
            field=models.NullBooleanField(verbose_name=' 保温炉 零件 => 感温棒'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row08d00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 保温炉 進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row08e00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 保温炉 進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row08f00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 保温炉 進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row08g00',
            field=models.NullBooleanField(verbose_name=' 保温炉 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row08g07',
            field=models.NullBooleanField(verbose_name=' 保温炉 備註說明 => 温度不准'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row09c00',
            field=models.CharField(default='.', max_length=99, verbose_name='控制系统 膜厚調節 零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row09c01',
            field=models.NullBooleanField(verbose_name='控制系统 膜厚調節 零件 => 开关'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row09d00',
            field=models.CharField(default='.', max_length=99, verbose_name='控制系统 膜厚調節 進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row09e00',
            field=models.CharField(default='.', max_length=99, verbose_name='控制系统 膜厚調節 進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row09f00',
            field=models.CharField(default='.', max_length=99, verbose_name='控制系统 膜厚調節 進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row09g00',
            field=models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row09g04',
            field=models.NullBooleanField(verbose_name='控制系统 膜厚調節 備註說明 => 無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row10c00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 主电箱 零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row10c01',
            field=models.NullBooleanField(verbose_name=' 主电箱 零件 => 电路板'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row10c02',
            field=models.NullBooleanField(verbose_name=' 主电箱 零件 => 保险丝'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row10c03',
            field=models.NullBooleanField(verbose_name=' 主电箱 零件 => 保温炉控制器'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row10d00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 主电箱 進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row10e00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 主电箱 進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row10f00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 主电箱 進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row10g00',
            field=models.NullBooleanField(verbose_name=' 主电箱 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row10g03',
            field=models.NullBooleanField(verbose_name=' 主电箱 備註說明 => 無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row11c00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 操作面板 零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row11c01',
            field=models.NullBooleanField(verbose_name=' 操作面板 零件 => 控制面板'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row11d00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 操作面板 進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row11e00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 操作面板 進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row11f00',
            field=models.CharField(default='.', max_length=99, verbose_name=' 操作面板 進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row11g00',
            field=models.NullBooleanField(verbose_name=' 操作面板 備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row11g03',
            field=models.NullBooleanField(verbose_name=' 操作面板 備註說明 => 無法修復'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row12c00',
            field=models.CharField(default='.', max_length=99, verbose_name='压射系统  零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row12c01',
            field=models.NullBooleanField(verbose_name='压射系统  零件 => 行程开关'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row12c02',
            field=models.NullBooleanField(verbose_name='压射系统  零件 => 射杆 连接板'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row12c03',
            field=models.NullBooleanField(verbose_name='压射系统  零件 => 料管'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row12c04',
            field=models.NullBooleanField(verbose_name='压射系统  零件 => 射杆接头'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row12d00',
            field=models.CharField(default='.', max_length=99, verbose_name='压射系统  進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row12e00',
            field=models.CharField(default='.', max_length=99, verbose_name='压射系统  進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row12f00',
            field=models.CharField(default='.', max_length=99, verbose_name='压射系统  進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row12g00',
            field=models.NullBooleanField(verbose_name='压射系统  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row12g08',
            field=models.NullBooleanField(verbose_name='压射系统  備註說明 => 接头断'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row13c00',
            field=models.CharField(default='.', max_length=99, verbose_name='澆注系統  零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row13c01',
            field=models.NullBooleanField(verbose_name='澆注系統  零件 => 链条齿轮'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row13c02',
            field=models.NullBooleanField(verbose_name='澆注系統  零件 => 链条'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row13c03',
            field=models.NullBooleanField(verbose_name='澆注系統  零件 => 铜套'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row13c04',
            field=models.NullBooleanField(verbose_name='澆注系統  零件 => 编码器'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row13c05',
            field=models.NullBooleanField(verbose_name='澆注系統  零件 => 接触开关'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row13d00',
            field=models.CharField(default='.', max_length=99, verbose_name='澆注系統  進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row13e00',
            field=models.CharField(default='.', max_length=99, verbose_name='澆注系統  進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row13f00',
            field=models.CharField(default='.', max_length=99, verbose_name='澆注系統  進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row13g00',
            field=models.NullBooleanField(verbose_name='澆注系統  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row13g04',
            field=models.NullBooleanField(verbose_name='澆注系統  備註說明 => 銅套磨損'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row14c00',
            field=models.CharField(default='.', max_length=99, verbose_name='油壓系統  零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row14c01',
            field=models.NullBooleanField(verbose_name='油壓系統  零件 => 油管'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row14c02',
            field=models.NullBooleanField(verbose_name='油壓系統  零件 => 過濾網'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row14c03',
            field=models.NullBooleanField(verbose_name='油壓系統  零件 => 油箱'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row14c04',
            field=models.NullBooleanField(verbose_name='油壓系統  零件 => 馬達'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row14c05',
            field=models.NullBooleanField(verbose_name='油壓系統  零件 => 電磁閥'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row14d00',
            field=models.CharField(default='.', max_length=99, verbose_name='油壓系統  進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row14e00',
            field=models.CharField(default='.', max_length=99, verbose_name='油壓系統  進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row14f00',
            field=models.CharField(default='.', max_length=99, verbose_name='油壓系統  進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row14g00',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row14g09',
            field=models.NullBooleanField(verbose_name='油壓系統  備註說明 => 閥心斷裂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row15c00',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑系統  零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row15c01',
            field=models.NullBooleanField(verbose_name='潤滑系統  零件 => 油嘴'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row15c02',
            field=models.NullBooleanField(verbose_name='潤滑系統  零件 => 分油器'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row15c03',
            field=models.NullBooleanField(verbose_name='潤滑系統  零件 => 油管'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row15c04',
            field=models.NullBooleanField(verbose_name='潤滑系統  零件 => 油泵'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row15d00',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑系統  進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row15e00',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑系統  進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row15f00',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑系統  進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row15g00',
            field=models.NullBooleanField(verbose_name='潤滑系統  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row15g03',
            field=models.NullBooleanField(verbose_name='潤滑系統  備註說明 => 泵心磨損'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row16c00',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣  零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row16c01',
            field=models.NullBooleanField(verbose_name='氮氣  零件 => 氮气钢瓶'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row16c02',
            field=models.NullBooleanField(verbose_name='氮氣  零件 => 氮气瓶油封'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row16c03',
            field=models.NullBooleanField(verbose_name='氮氣  零件 => 轴承带'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row16d00',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣  進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row16e00',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣  進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row16f00',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣  進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row16g00',
            field=models.NullBooleanField(verbose_name='氮氣  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row16g04',
            field=models.NullBooleanField(verbose_name='氮氣  備註說明 => 磨损'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row17c00',
            field=models.CharField(default='.', max_length=99, verbose_name='锁模系统  零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row17c01',
            field=models.NullBooleanField(verbose_name='锁模系统  零件 => 电子尺'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row17d00',
            field=models.CharField(default='.', max_length=99, verbose_name='锁模系统  進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row17e00',
            field=models.CharField(default='.', max_length=99, verbose_name='锁模系统  進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row17f00',
            field=models.CharField(default='.', max_length=99, verbose_name='锁模系统  進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row17g00',
            field=models.NullBooleanField(verbose_name='锁模系统  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row17g01',
            field=models.NullBooleanField(verbose_name='锁模系统  備註說明 => 读数不准'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row18c00',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧  零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row18c01',
            field=models.NullBooleanField(verbose_name='自動噴霧  零件 => 雾化器'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row18c02',
            field=models.NullBooleanField(verbose_name='自動噴霧  零件 => 喷雾机板'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row18c03',
            field=models.NullBooleanField(verbose_name='自動噴霧  零件 => 铜管'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row18c04',
            field=models.NullBooleanField(verbose_name='自動噴霧  零件 => 电磁阀'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row18c05',
            field=models.NullBooleanField(verbose_name='自動噴霧  零件 => 缓冲器'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row18d00',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧  進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row18e00',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧  進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row18f00',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧  進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row18g00',
            field=models.NullBooleanField(verbose_name='自動噴霧  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row18g06',
            field=models.NullBooleanField(verbose_name='自動噴霧  備註說明 => 漏水'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row19c00',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出  零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row19c01',
            field=models.NullBooleanField(verbose_name='自動取出  零件 => 取件机手臂'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row19c02',
            field=models.NullBooleanField(verbose_name='自動取出  零件 => 缓冲器'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row19c03',
            field=models.NullBooleanField(verbose_name='自動取出  零件 => 夹手'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row19c04',
            field=models.NullBooleanField(verbose_name='自動取出  零件 => 轴承'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row19c05',
            field=models.NullBooleanField(verbose_name='自動取出  零件 => 马达'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row19d00',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出  進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row19e00',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出  進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row19f00',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出  進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row19g00',
            field=models.NullBooleanField(verbose_name='自動取出  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row19g05',
            field=models.NullBooleanField(verbose_name='自動取出  備註說明 => 内部烧坏'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20c00',
            field=models.CharField(default='.', max_length=99, verbose_name='模具  零件'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20c01',
            field=models.NullBooleanField(verbose_name='模具  零件 => 模芯'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20c02',
            field=models.NullBooleanField(verbose_name='模具  零件 => 顶针'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20c03',
            field=models.NullBooleanField(verbose_name='模具  零件 => 滑块'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20c04',
            field=models.NullBooleanField(verbose_name='模具  零件 => 定模仁'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20c05',
            field=models.NullBooleanField(verbose_name='模具  零件 => 动模仁'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20c06',
            field=models.NullBooleanField(verbose_name='模具  零件 => 油缸'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20d00',
            field=models.CharField(default='.', max_length=99, verbose_name='模具  進度一'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20e00',
            field=models.CharField(default='.', max_length=99, verbose_name='模具  進度二'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20f00',
            field=models.CharField(default='.', max_length=99, verbose_name='模具  進度三'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20g00',
            field=models.NullBooleanField(verbose_name='模具  備註說明  正常'),
        ),
        migrations.AddField(
            model_name='item008',
            name='row20g06',
            field=models.NullBooleanField(verbose_name='模具  備註說明 => 待修模'),
        ),
    ]
