# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0051_auto_20160827_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item008',
            name='row12c02',
            field=models.NullBooleanField(verbose_name='压射系统  零件 => 射杆连接板'),
        ),
    ]
