# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0052_auto_20160828_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item008',
            name='row01c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row02c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row03c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row04c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row05c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row06c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row07c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row08c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row09c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row10c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row11c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row12c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row13c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row14c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row15c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row16c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row17c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row18c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row19c00',
        ),
        migrations.RemoveField(
            model_name='item008',
            name='row20c00',
        ),
    ]
