# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0053_auto_20160828_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='item008',
            name='row01g03test',
            field=models.BooleanField(default=False, verbose_name='外部主件 格林柱 備註說明 => TESTING'),
        ),
    ]
