# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0054_item008_row01g03test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item008',
            name='row01g03test',
        ),
        migrations.AlterField(
            model_name='item008',
            name='row01c01',
            field=models.BooleanField(default=False, verbose_name='外部主件 格林柱 零件 => 格林柱'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row01g01',
            field=models.BooleanField(default=False, verbose_name='外部主件 格林柱 備註說明 => 磨損'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row01g02',
            field=models.BooleanField(default=False, verbose_name='外部主件 格林柱 備註說明 => 無法修復'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row02c01',
            field=models.BooleanField(default=False, verbose_name=' 機架底座 零件 => 機架底座'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row02g01',
            field=models.BooleanField(default=False, verbose_name=' 機架底座 備註說明 => 磨損'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row02g02',
            field=models.BooleanField(default=False, verbose_name=' 機架底座 備註說明 => 裂縫'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row02g03',
            field=models.BooleanField(default=False, verbose_name=' 機架底座 備註說明 => 漏油'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row03c01',
            field=models.BooleanField(default=False, verbose_name=' 模板(定) 零件 => 模板(定)'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row03g01',
            field=models.BooleanField(default=False, verbose_name=' 模板(定) 備註說明 => 平面變型'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row03g02',
            field=models.BooleanField(default=False, verbose_name=' 模板(定) 備註說明 => 無法修復'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row04c01',
            field=models.BooleanField(default=False, verbose_name=' 模板(動) 零件 => 模板(動)'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row04g01',
            field=models.BooleanField(default=False, verbose_name=' 模板(動) 備註說明 => 平面變型'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row04g02',
            field=models.BooleanField(default=False, verbose_name=' 模板(動) 備註說明 => 無法修復'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row05c01',
            field=models.BooleanField(default=False, verbose_name=' 合模 零件 => 油路板'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row05c02',
            field=models.BooleanField(default=False, verbose_name=' 合模 零件 => 合模油缸'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row05g01',
            field=models.BooleanField(default=False, verbose_name=' 合模 備註說明 => 合模缸漏油'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row05g02',
            field=models.BooleanField(default=False, verbose_name=' 合模 備註說明 => 合模缸螺旋斷裂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row05g03',
            field=models.BooleanField(default=False, verbose_name=' 合模 備註說明 => 合模活塞磨損'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row05g04',
            field=models.BooleanField(default=False, verbose_name=' 合模 備註說明 => 無法修復'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row06c01',
            field=models.BooleanField(default=False, verbose_name=' 曲軸 零件 => 曲轴销'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row06c02',
            field=models.BooleanField(default=False, verbose_name=' 曲軸 零件 => 衬套'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row06g01',
            field=models.BooleanField(default=False, verbose_name=' 曲軸 備註說明 => 磨損'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row06g02',
            field=models.BooleanField(default=False, verbose_name=' 曲軸 備註說明 => 無法修復'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row07c01',
            field=models.BooleanField(default=False, verbose_name=' 鋼帶 零件 => 鋼帶'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row07g01',
            field=models.BooleanField(default=False, verbose_name=' 鋼帶 備註說明 => 磨損'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row07g02',
            field=models.BooleanField(default=False, verbose_name=' 鋼帶 備註說明 => 斷裂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row07g03',
            field=models.BooleanField(default=False, verbose_name=' 鋼帶 備註說明 => 無法修復'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08c01',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 零件 => 炉盖'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08c02',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 零件 => 加热管'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08c03',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 零件 => 电线'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08c04',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 零件 => 感温棒'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08g01',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 備註說明 => 磨損'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08g02',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 備註說明 => 斷裂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08g03',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 備註說明 => 無法修復'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08g04',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 備註說明 => 炉盖损坏'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08g05',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 備註說明 => 加热管断'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08g06',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 備註說明 => 电路断'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08g07',
            field=models.BooleanField(default=False, verbose_name=' 保温炉 備註說明 => 温度不准'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row09c01',
            field=models.BooleanField(default=False, verbose_name='控制系统 膜厚調節 零件 => 开关'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row09g01',
            field=models.BooleanField(default=False, verbose_name='控制系统 膜厚調節 備註說明 => 開關損壞'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row09g02',
            field=models.BooleanField(default=False, verbose_name='控制系统 膜厚調節 備註說明 => 線路不通'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row09g03',
            field=models.BooleanField(default=False, verbose_name='控制系统 膜厚調節 備註說明 => 短路'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row09g04',
            field=models.BooleanField(default=False, verbose_name='控制系统 膜厚調節 備註說明 => 無法修復'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row10c01',
            field=models.BooleanField(default=False, verbose_name=' 主电箱 零件 => 电路板'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row10c02',
            field=models.BooleanField(default=False, verbose_name=' 主电箱 零件 => 保险丝'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row10c03',
            field=models.BooleanField(default=False, verbose_name=' 主电箱 零件 => 保温炉控制器'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row10g01',
            field=models.BooleanField(default=False, verbose_name=' 主电箱 備註說明 => 保险丝烧坏'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row10g02',
            field=models.BooleanField(default=False, verbose_name=' 主电箱 備註說明 => 線路不通'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row10g03',
            field=models.BooleanField(default=False, verbose_name=' 主电箱 備註說明 => 無法修復'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row11c01',
            field=models.BooleanField(default=False, verbose_name=' 操作面板 零件 => 控制面板'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row11g01',
            field=models.BooleanField(default=False, verbose_name=' 操作面板 備註說明 => 按键损坏'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row11g02',
            field=models.BooleanField(default=False, verbose_name=' 操作面板 備註說明 => 系统坏'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row11g03',
            field=models.BooleanField(default=False, verbose_name=' 操作面板 備註說明 => 無法修復'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12c01',
            field=models.BooleanField(default=False, verbose_name='压射系统  零件 => 行程开关'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12c02',
            field=models.BooleanField(default=False, verbose_name='压射系统  零件 => 射杆连接板'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12c03',
            field=models.BooleanField(default=False, verbose_name='压射系统  零件 => 料管'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12c04',
            field=models.BooleanField(default=False, verbose_name='压射系统  零件 => 射杆接头'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12g01',
            field=models.BooleanField(default=False, verbose_name='压射系统  備註說明 => 無壓力'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12g02',
            field=models.BooleanField(default=False, verbose_name='压射系统  備註說明 => 線路不通'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12g03',
            field=models.BooleanField(default=False, verbose_name='压射系统  備註說明 => 壓射缸漏油'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12g04',
            field=models.BooleanField(default=False, verbose_name='压射系统  備註說明 => 射杆彎曲'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12g05',
            field=models.BooleanField(default=False, verbose_name='压射系统  備註說明 => 连接板断裂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12g06',
            field=models.BooleanField(default=False, verbose_name='压射系统  備註說明 => 开关无信号'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12g07',
            field=models.BooleanField(default=False, verbose_name='压射系统  備註說明 => 料管磨损'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12g08',
            field=models.BooleanField(default=False, verbose_name='压射系统  備註說明 => 接头断'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row13c01',
            field=models.BooleanField(default=False, verbose_name='澆注系統  零件 => 链条齿轮'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row13c02',
            field=models.BooleanField(default=False, verbose_name='澆注系統  零件 => 链条'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row13c03',
            field=models.BooleanField(default=False, verbose_name='澆注系統  零件 => 铜套'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row13c04',
            field=models.BooleanField(default=False, verbose_name='澆注系統  零件 => 编码器'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row13c05',
            field=models.BooleanField(default=False, verbose_name='澆注系統  零件 => 接触开关'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row13g01',
            field=models.BooleanField(default=False, verbose_name='澆注系統  備註說明 => 链条断'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row13g02',
            field=models.BooleanField(default=False, verbose_name='澆注系統  備註說明 => 齿轮滑牙斷'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row13g03',
            field=models.BooleanField(default=False, verbose_name='澆注系統  備註說明 => 編碼器異常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row13g04',
            field=models.BooleanField(default=False, verbose_name='澆注系統  備註說明 => 銅套磨損'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14c01',
            field=models.BooleanField(default=False, verbose_name='油壓系統  零件 => 油管'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14c02',
            field=models.BooleanField(default=False, verbose_name='油壓系統  零件 => 過濾網'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14c03',
            field=models.BooleanField(default=False, verbose_name='油壓系統  零件 => 油箱'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14c04',
            field=models.BooleanField(default=False, verbose_name='油壓系統  零件 => 馬達'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14c05',
            field=models.BooleanField(default=False, verbose_name='油壓系統  零件 => 電磁閥'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14g01',
            field=models.BooleanField(default=False, verbose_name='油壓系統  備註說明 => 破損'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14g02',
            field=models.BooleanField(default=False, verbose_name='油壓系統  備註說明 => 斷裂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14g03',
            field=models.BooleanField(default=False, verbose_name='油壓系統  備註說明 => 接頭滑絲'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14g04',
            field=models.BooleanField(default=False, verbose_name='油壓系統  備註說明 => 堵塞'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14g05',
            field=models.BooleanField(default=False, verbose_name='油壓系統  備註說明 => 油品變質'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14g06',
            field=models.BooleanField(default=False, verbose_name='油壓系統  備註說明 => 磨損'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14g07',
            field=models.BooleanField(default=False, verbose_name='油壓系統  備註說明 => 軸心斷裂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14g08',
            field=models.BooleanField(default=False, verbose_name='油壓系統  備註說明 => 線路不通'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14g09',
            field=models.BooleanField(default=False, verbose_name='油壓系統  備註說明 => 閥心斷裂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row15c01',
            field=models.BooleanField(default=False, verbose_name='潤滑系統  零件 => 油嘴'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row15c02',
            field=models.BooleanField(default=False, verbose_name='潤滑系統  零件 => 分油器'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row15c03',
            field=models.BooleanField(default=False, verbose_name='潤滑系統  零件 => 油管'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row15c04',
            field=models.BooleanField(default=False, verbose_name='潤滑系統  零件 => 油泵'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row15g01',
            field=models.BooleanField(default=False, verbose_name='潤滑系統  備註說明 => 管道不通'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row15g02',
            field=models.BooleanField(default=False, verbose_name='潤滑系統  備註說明 => 管道斷裂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row15g03',
            field=models.BooleanField(default=False, verbose_name='潤滑系統  備註說明 => 泵心磨損'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row16c01',
            field=models.BooleanField(default=False, verbose_name='氮氣  零件 => 氮气钢瓶'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row16c02',
            field=models.BooleanField(default=False, verbose_name='氮氣  零件 => 氮气瓶油封'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row16c03',
            field=models.BooleanField(default=False, verbose_name='氮氣  零件 => 轴承带'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row16g01',
            field=models.BooleanField(default=False, verbose_name='氮氣  備註說明 => 鋼瓶裂縫'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row16g02',
            field=models.BooleanField(default=False, verbose_name='氮氣  備註說明 => 壓力過高'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row16g03',
            field=models.BooleanField(default=False, verbose_name='氮氣  備註說明 => 壓力過低'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row16g04',
            field=models.BooleanField(default=False, verbose_name='氮氣  備註說明 => 磨损'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row17c01',
            field=models.BooleanField(default=False, verbose_name='锁模系统  零件 => 电子尺'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row17g01',
            field=models.BooleanField(default=False, verbose_name='锁模系统  備註說明 => 读数不准'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18c01',
            field=models.BooleanField(default=False, verbose_name='自動噴霧  零件 => 雾化器'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18c02',
            field=models.BooleanField(default=False, verbose_name='自動噴霧  零件 => 喷雾机板'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18c03',
            field=models.BooleanField(default=False, verbose_name='自動噴霧  零件 => 铜管'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18c04',
            field=models.BooleanField(default=False, verbose_name='自動噴霧  零件 => 电磁阀'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18c05',
            field=models.BooleanField(default=False, verbose_name='自動噴霧  零件 => 缓冲器'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18g01',
            field=models.BooleanField(default=False, verbose_name='自動噴霧  備註說明 => 霧化器損壞'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18g02',
            field=models.BooleanField(default=False, verbose_name='自動噴霧  備註說明 => 線路不通'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18g03',
            field=models.BooleanField(default=False, verbose_name='自動噴霧  備註說明 => 緩衝彈簧斷裂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18g04',
            field=models.BooleanField(default=False, verbose_name='自動噴霧  備註說明 => 喷头螺丝滑牙'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18g05',
            field=models.BooleanField(default=False, verbose_name='自動噴霧  備註說明 => 断裂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18g06',
            field=models.BooleanField(default=False, verbose_name='自動噴霧  備註說明 => 漏水'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row19c01',
            field=models.BooleanField(default=False, verbose_name='自動取出  零件 => 取件机手臂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row19c02',
            field=models.BooleanField(default=False, verbose_name='自動取出  零件 => 缓冲器'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row19c03',
            field=models.BooleanField(default=False, verbose_name='自動取出  零件 => 夹手'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row19c04',
            field=models.BooleanField(default=False, verbose_name='自動取出  零件 => 轴承'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row19c05',
            field=models.BooleanField(default=False, verbose_name='自動取出  零件 => 马达'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row19g01',
            field=models.BooleanField(default=False, verbose_name='自動取出  備註說明 => 手臂断裂'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row19g02',
            field=models.BooleanField(default=False, verbose_name='自動取出  備註說明 => 夹手磨损'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row19g03',
            field=models.BooleanField(default=False, verbose_name='自動取出  備註說明 => 缓冲器坏'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row19g04',
            field=models.BooleanField(default=False, verbose_name='自動取出  備註說明 => 手臂轴承坏'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row19g05',
            field=models.BooleanField(default=False, verbose_name='自動取出  備註說明 => 内部烧坏'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20c01',
            field=models.BooleanField(default=False, verbose_name='模具  零件 => 模芯'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20c02',
            field=models.BooleanField(default=False, verbose_name='模具  零件 => 顶针'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20c03',
            field=models.BooleanField(default=False, verbose_name='模具  零件 => 滑块'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20c04',
            field=models.BooleanField(default=False, verbose_name='模具  零件 => 定模仁'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20c05',
            field=models.BooleanField(default=False, verbose_name='模具  零件 => 动模仁'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20c06',
            field=models.BooleanField(default=False, verbose_name='模具  零件 => 油缸'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20g01',
            field=models.BooleanField(default=False, verbose_name='模具  備註說明 => 尺寸NG'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20g02',
            field=models.BooleanField(default=False, verbose_name='模具  備註說明 => 模崩'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20g03',
            field=models.BooleanField(default=False, verbose_name='模具  備註說明 => 模芯斷'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20g04',
            field=models.BooleanField(default=False, verbose_name='模具  備註說明 => 顶针斷'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20g05',
            field=models.BooleanField(default=False, verbose_name='模具  備註說明 => 重覆修模'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20g06',
            field=models.BooleanField(default=False, verbose_name='模具  備註說明 => 待修模'),
        ),
    ]
