# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0056_auto_20160828_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item008',
            name='row01g00',
            field=models.BooleanField(default=True, verbose_name='外部主件 格林柱 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row02g00',
            field=models.BooleanField(default=True, verbose_name=' 機架底座 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row03g00',
            field=models.BooleanField(default=True, verbose_name=' 模板(定) 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row04g00',
            field=models.BooleanField(default=True, verbose_name=' 模板(動) 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row05g00',
            field=models.BooleanField(default=True, verbose_name=' 合模 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row06g00',
            field=models.BooleanField(default=True, verbose_name=' 曲軸 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row07g00',
            field=models.BooleanField(default=True, verbose_name=' 鋼帶 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row08g00',
            field=models.BooleanField(default=True, verbose_name=' 保温炉 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row09g00',
            field=models.BooleanField(default=True, verbose_name='控制系统 膜厚調節 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row10g00',
            field=models.BooleanField(default=True, verbose_name=' 主电箱 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row11g00',
            field=models.BooleanField(default=True, verbose_name=' 操作面板 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row12g00',
            field=models.BooleanField(default=True, verbose_name='压射系统  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row13g00',
            field=models.BooleanField(default=True, verbose_name='澆注系統  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row14g00',
            field=models.BooleanField(default=True, verbose_name='油壓系統  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row15g00',
            field=models.BooleanField(default=True, verbose_name='潤滑系統  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row16g00',
            field=models.BooleanField(default=True, verbose_name='氮氣  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row17g00',
            field=models.BooleanField(default=True, verbose_name='锁模系统  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row18g00',
            field=models.BooleanField(default=True, verbose_name='自動噴霧  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row19g00',
            field=models.BooleanField(default=True, verbose_name='自動取出  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='row20g00',
            field=models.BooleanField(default=True, verbose_name='模具  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row01g00',
            field=models.BooleanField(default=True, verbose_name='外部主件 格林柱 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row02g00',
            field=models.BooleanField(default=True, verbose_name=' 機架底座 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row03g00',
            field=models.BooleanField(default=True, verbose_name=' 模板(定) 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row04g00',
            field=models.BooleanField(default=True, verbose_name=' 模板(動) 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row05g00',
            field=models.BooleanField(default=True, verbose_name=' 合模 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row06g00',
            field=models.BooleanField(default=True, verbose_name=' 曲軸 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row07g00',
            field=models.BooleanField(default=True, verbose_name=' 鋼帶 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row08g00',
            field=models.BooleanField(default=True, verbose_name=' 保温炉 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row09g00',
            field=models.BooleanField(default=True, verbose_name='控制系统 膜厚調節 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row10g00',
            field=models.BooleanField(default=True, verbose_name=' 主电箱 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row11g00',
            field=models.BooleanField(default=True, verbose_name=' 操作面板 備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row12g00',
            field=models.BooleanField(default=True, verbose_name='压射系统  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row13g00',
            field=models.BooleanField(default=True, verbose_name='澆注系統  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row14g00',
            field=models.BooleanField(default=True, verbose_name='油壓系統  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row15g00',
            field=models.BooleanField(default=True, verbose_name='潤滑系統  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row16g00',
            field=models.BooleanField(default=True, verbose_name='氮氣  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row17g00',
            field=models.BooleanField(default=True, verbose_name='锁模系统  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row18g00',
            field=models.BooleanField(default=True, verbose_name='自動噴霧  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row19g00',
            field=models.BooleanField(default=True, verbose_name='自動取出  備註說明  正常'),
        ),
        migrations.AlterField(
            model_name='item009',
            name='row20g00',
            field=models.BooleanField(default=True, verbose_name='模具  備註說明  正常'),
        ),
    ]
