# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0057_auto_20160829_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='item008',
            name='headere',
            field=models.DateTimeField(auto_now=True, verbose_name='資料維護日期時間'),
        ),
        migrations.AddField(
            model_name='item008',
            name='headerf',
            field=models.CharField(choices=[('正常生产', '正常生产'), ('设备故障', '设备故障'), ('无订单', '无订单'), ('无人操作', '无人操作'), ('外发大修', '外发大修'), ('无模具', '无模具')], default='.', max_length=99, verbose_name='机台状态'),
        ),
        migrations.AlterField(
            model_name='item008',
            name='headerd',
            field=models.DateField(verbose_name='到廠日期'),
        ),
    ]
