# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0059_auto_20160829_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item005',
            name='stat1',
            field=models.CharField(default='.', max_length=250, verbose_name='進度一'),
        ),
        migrations.AlterField(
            model_name='item005',
            name='stat2',
            field=models.CharField(default='.', max_length=250, verbose_name='進度二'),
        ),
        migrations.AlterField(
            model_name='item005',
            name='stat3',
            field=models.CharField(default='.', max_length=250, verbose_name='進度三'),
        ),
        migrations.AlterField(
            model_name='item006',
            name='stat1',
            field=models.CharField(default='.', max_length=250, verbose_name='進度一'),
        ),
        migrations.AlterField(
            model_name='item006',
            name='stat2',
            field=models.CharField(default='.', max_length=250, verbose_name='進度二'),
        ),
        migrations.AlterField(
            model_name='item006',
            name='stat3',
            field=models.CharField(default='.', max_length=250, verbose_name='進度三'),
        ),
    ]
