# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0034_auto_20160823_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item004',
            name='f12',
            field=models.CharField(default='.', max_length=99, verbose_name='模具壽命'),
        ),
    ]
