# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0038_auto_20160823_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item003v2',
            name='headerd',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
